# Generated by Django 4.1.3 on 2022-11-21 07:17

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0005_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='cover',
        ),
        migrations.AddField(
            model_name='car',
            name='info',
            field=tinymce.models.HTMLField(default='info', verbose_name='info'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo', verbose_name='photo'),
        ),
    ]
